# Generated by Django 5.2.7 on 2026-09-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=40)),
                ('severity', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('rgb_image', models.ImageField(blank=True, upload_to='scans/rgb/')),
                ('thermal_image', models.ImageField(blank=True, upload_to='scans/thermal/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
