services:
  - type: web
    name: agriscan-inference-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MODEL_PATH
        value: /app/model_artifacts/sugarcane_mobilenet.pt